[Vulkan_Headers]
git-tree-sha1 = "2172e04648d8f007f61b8348c3172efb89619c1c"

    [[Vulkan_Headers.download]]
    sha256 = "7230c2aba43383dc410ba1fe036d3254dcd2d4450d2cd14ae8d211c61ebe5197"
    url = "https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.2.177+0/Vulkan_Headers.v1.2.177.any.tar.gz"
