[Vulkan_Headers]
git-tree-sha1 = "8bfcdb8832078af6cc9667780f1d15e9897c18bf"

    [[Vulkan_Headers.download]]
    sha256 = "f7953a556cae59410875a77b0a998f7190e3aa04c64814d609679d6ccaa16ca9"
    url = "https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.243+0/Vulkan_Headers.v1.3.243.any.tar.gz"
