[Vulkan_Headers]
git-tree-sha1 = "aa857244a909c74c3f85ed29fc9c76daa501737e"

    [[Vulkan_Headers.download]]
    sha256 = "2fe9d00b5741e5066ae41359ce4ce0816f71f4df6a688194bc81e438394115d7"
    url = "https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.3.207+0/Vulkan_Headers.v1.3.207.any.tar.gz"
