[Vulkan_Headers]
git-tree-sha1 = "215ab5861ec5093af6894cb45b1c8739986dc0c2"

    [[Vulkan_Headers.download]]
    sha256 = "f9c08fbec07312954102dd7eca480d734ad8adf8eef0ca7f86ad48a4762831cb"
    url = "https://github.com/JuliaBinaryWrappers/Vulkan_Headers_jll.jl/releases/download/Vulkan_Headers-v1.4.312+0/Vulkan_Headers.v1.4.312.any.tar.gz"
